//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.ModelConfiguration.Conventions;

namespace AdminConsole.Models
{
    public partial class AdminConsoleEntities : DbContext
    {
        //public AdminConsoleEntities()
        //    : base("name=AdminConsoleEntities")
        //{
        //}

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            modelBuilder.Conventions.Remove<IncludeMetadataConvention>();
        }
    
        public DbSet<Desktop> DesktopTypes { get; set; }
        public DbSet<TargetContainer> TargetContainers { get; set; }
        public DbSet<Target> Targets { get; set; }
        public DbSet<TargetType> TargetTypes { get; set; }
    }
}
