//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AdminConsole.Models
{
    public partial class Target
    {
        public Target()
        {
            this.TargetContainers = new HashSet<TargetContainer>();
        }
    
        public int Id { get; set; }
        public string Address { get; set; }
        public string TargetType_TargetTypeCode { get; set; }

        [ForeignKey("TargetType_TargetTypeCode")]
        public virtual TargetType TargetType { get; set; }
        public virtual ICollection<TargetContainer> TargetContainers { get; set; }
    }
    
}
