//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace AdminConsole.Models
{
    public partial class TargetContainer
    {
        public TargetContainer()
        {
            this.ChildTargetContainers = new HashSet<TargetContainer>();
            this.Targets = new HashSet<Target>();
        }
    
        [Key]
        public int Id { get; set; }
        public string Description { get; set; }
        public short Sequence { get; set; }
        public bool InheritsParent { get; set; }
        public string ExtendedProperty { get; set; }
        public int? ParentTargetContainer_Id { get; set; }
        public string DesktopType_DesktopCode { get; set; }
    
        [ForeignKey("DesktopType_DesktopCode")]
        public virtual Desktop Desktop { get; set; }

        public virtual ICollection<TargetContainer> ChildTargetContainers { get; set; }

        
        [ForeignKey("ParentTargetContainer_Id")]
        public virtual TargetContainer ParentTargetContainer { get; set; }

        public virtual ICollection<Target> Targets { get; set; }
    }
    
}
